log:
  level: debug
  disable_sentry: true

db:
  url: db_url

listener:
  addr: :8000

issuer:
  base_url: "http://issuer"

civic:
  # ID of the gatekeeperNetwork on gateway contract. You can find info about it in Civic doc.
  # Use this one id for the Uniqueness check. aka gatekeeper_network_slot_id
  gatekeeper_network_id: 10
  # The contract address is the same for every chain
  gateway_token_contract: "0xF65b6396dF6B7e2D8a6270E3AB6c7BB08BAEF22E"
  eth_rpc_url: "https://..."
  xdc_rpc_url: "https://..."
  polygon_rpc_url: "https://..."
  arbitrum_rpc_url: "https://..."

unstoppable_domains:
  auth_base_url: "https://auth.unstoppabledomains.com"

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: kyc-service
  service_port: 80
