log:
  level: debug
  disable_sentry: true

db:
  url: db_url

listener:
  addr: :8000

issuer:
  base_url: "http://issuer"

unstoppable_domains:
  auth_base_url: "https://auth.unstoppabledomains.com"

worldcoin:
  base_url: "https://id.worldcoin.org"

gitcoin:
  base_url: "https://api.scorer.gitcoin.co/registry"
  api_key:
  scorer_id:
  gate_score: 15
  get_score_max_retries: 3
  skip_sig_check: true

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: kyc-service
  service_port: 80
