log:
  level: debug
  disable_sentry: true

db:
  url: db_url

listener:
  addr: :8000

issuer:
  base_url: "http://issuer"

unstoppable_domains:
  auth_base_url: "https://auth.unstoppabledomains.com"

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: kyc-service
  service_port: 80
