log:
  level: debug
  disable_sentry: true

db:
  url: db_url

listener:
  addr: :8000

issuer:
  base_url: "http://issuer"
  auth_username: ""
  auth_password: ""
  schema_type: ""
  schema_url: ""

civic:
  # ID of the gatekeeperNetwork on gateway contract. You can find info about it in Civic doc.
  # Use this one id for the Uniqueness check. aka gatekeeper_network_slot_id
  captcha_gatekeeper_network_id: 4
  uniqueness_gatekeeper_network_id: 10
  # The contract address is the same for every chain
  gateway_token_contract: "0xF65b6396dF6B7e2D8a6270E3AB6c7BB08BAEF22E"
  eth_rpc_url: "https://..."
  xdc_rpc_url: "https://..."
  polygon_rpc_url: "https://..."
  arbitrum_rpc_url: "https://..."
  skip_sig_check: false

unstoppable_domains:
  auth_base_url: "https://auth.unstoppabledomains.com"

worldcoin:
  base_url: "https://id.worldcoin.org"

gitcoin_passport:
  base_url: "https://api.scorer.gitcoin.co/registry"
  api_key: "..."
  scorer_id: 12
  gate_score: 15
  get_score_max_retries: 3
  skip_sig_check: false

kleros:
  eth_rpc_url:
  proof_of_humanity_contract:

humanornot_svc:
  nonce_life_time: 30m

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: humanornot-svc
  service_port: 80
